dfx canister call sustainations_dao createQuestEngine '(record{id="engine";name="Quest Engine";description="Test Description";price = 0;images="Lake.png"})'

dfx canister call sustainations_dao createEventEngine '(record{id="ev1";questId="engine";description="On the bench, there is a question. Find the correct answer to continue or else. “What is able to go up a chimney when down but unable to go down a chimney when up?”";locationName="spring";destinationName="summer"})'
dfx canister call sustainations_dao createEventEngine '(record{id="ev2";questId="engine";description="On the bench, there is another question. Find the correct answer to continue or else. “First you eat me, then you get eaten. What am I?”";locationName="summer";destinationName="autumn"})'
dfx canister call sustainations_dao createEventEngine '(record{id="ev3";questId="engine";description="Same bench, different season, different question. Find the correct answer to continue or else. “This belongs to you, but everyone else uses it.”";locationName="autumn";destinationName="wintecreateeventenr"})'


dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo1";eventId="ev1";description="An umbrella";requireItemId="i7";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'
dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo2";eventId="ev1";description="A parachute ";requireItemId="null";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'
dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo3";eventId="ev2";description="An apple";requireItemId="i8";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'
dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo4";eventId="ev2";description="A hook";requireItemId="null";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'
dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo5";eventId="ev3";description="Your phone";requireItemId="i9";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'
dfx canister call sustainations_dao createEventOptionEngine '(record{id="eo6";eventId="ev3";description="Your wallet ";requireItemId="null";lossHP=2.0;lossMana=2.0;lossStamina=2.0;lossMorale=2.0;riskChance=0.0;riskLost="null";lossOther="null";gainExp=0;gainHP=0.0;gainStamina=0.0;gainMorale=0.0;gainMana=0.0;luckyChance=0.0;gainByLuck="null";gainOther=0.0})'

dfx canister call sustainations_dao createScene '("engine", record{id="s1"; idEvent="ee1"; front="development/engine/scene1/front.png"; mid="development/engine/scene1/mid.png"; back="development/engine/scene1/back.png"; obstacle="development/engine/scene1/obstacle.png"})'
dfx canister call sustainations_dao createScene '("engine", record{id="s2"; idEvent="ee1"; front="development/engine/scene2/front.png"; mid="development/engine/scene2/mid.png"; back="development/engine/scene2/back.png"; obstacle="development/engine/scene2/obstacle.png"})'
dfx canister call sustainations_dao createScene '("engine", record{id="s3"; idEvent="ee1"; front="development/engine/scene3/front.png"; mid="development/engine/scene3/mid.png"; back="development/engine/scene3/back.png"; obstacle="development/engine/scene3/obstacle.png"})'