dfx canister call sustainations_dao updateSeed '(record{id="s1tomato";harvestedProductId="p1tomato";materialId="m3tomato_seed";rowSize=1;columnSize=1;name="Tomato_Seed";description="Tomato Seed";waitTime=120;expiryTime=0;grownCondition="none";minAmount=1;maxAmount=1;})'
dfx canister call sustainations_dao updateSeed '(record{id="s2carrot";harvestedProductId="p2carrot";materialId="m4carrot_seed";rowSize=1;columnSize=1;name="Carrot_Seed";description="Carrot Seed";waitTime=120;expiryTime=0;grownCondition="none";minAmount=1;maxAmount=1;})'
dfx canister call sustainations_dao updateSeed '(record{id="s3wheat";harvestedProductId="p3wheat";materialId="m5wheat_seed";rowSize=1;columnSize=1;name="Wheat_Seed";description="Wheat Seed";waitTime=120;expiryTime=0;grownCondition="none";minAmount=1;maxAmount=1;})'
dfx canister call sustainations_dao restoreProducts
dfx canister call sustainations_dao deleteUsableItem '("ui5")'
dfx canister call sustainations_dao deleteUsableItem '("ui6")'
dfx canister call sustainations_dao deleteUsableItem '("ui7")'
dfx canister call sustainations_dao deleteUsableItem '("ui8")'
dfx canister call sustainations_dao createUsableItem '(record {id ="ui5";increaseStamina = 3.0;name ="Super Potion";increaseMana = 3.0;effect = "none";increaseMorale = 3.0;increaseHP = 3.0;image = "test.jpg";})'
dfx canister call sustainations_dao updateUsableItem '(record{id="ui1";name="HP_Potion";image="test.jpg";increaseStamina=0.0;increaseHP=7.0;increaseMorale=0.0;increaseMana=0.0;effect="none"})'
dfx canister call sustainations_dao updateUsableItem '(record{id="ui2";name="Stamina_Potion";image="test.jpg";increaseStamina=7.0;increaseHP=0.0;increaseMorale=0.0;increaseMana=0.0;effect="none"})'
dfx canister call sustainations_dao updateUsableItem '(record{id="ui3";name="Mana_Potion";image="test.jpg";increaseStamina=0.0;increaseHP=0.0;increaseMorale=0.0;increaseMana=7.0;effect="none"})'
dfx canister call sustainations_dao updateUsableItem '(record{id="ui4";name="Morale_Potion";image="test.jpg";increaseStamina=0.0;increaseHP=0.0;increaseMorale=7.0;increaseMana=0.0;effect="none"})'
dfx canister call sustainations_dao updateUsableItem '(record{id="ui5";name="Super_Potion";image="test.jpg";increaseStamina=3.0;increaseHP=3.0;increaseMorale=3.0;increaseMana=3.0;effect="none"})'